trigger:
  branches:
    include:
    - '*'
    exclude:
      - master

variables:
- group: az_subscription

steps:

- task: TerraformInstaller@0
  displayName: 'Install terraform 0.12.20'
  inputs:
    terraformVersion: '0.12.20'

- task: TerraformTaskV1@0
  displayName: 'Terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: '-no-color'
    backendServiceArm: '$(subscription)'
    backendAzureRmResourceGroupName: 'cedi_rg'
    backendAzureRmStorageAccountName: '$(storrageaccount)'
    backendAzureRmContainerName: 'terraformcontainer'
    backendAzureRmKey: 'sharedstate.tfstate'

- task: TerraformTaskV1@0
  displayName: 'Terraform validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    commandOptions: '-no-color'
