baseURL = "https://cedi.dev/"
languageCode = "en-us"
title = "cedi.dev"
theme = "hugo-coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "cedi"

[params]
    author = "Cedric Kienzler"
    info = "Software Engineer and Photographer"
    description = "Cedrics personal website"
    keywords = "blog,developer"
    #avatarurl = "https://avatars0.githubusercontent.com/u/1952599?s=460&v=4"
    avatarurl = "avatar.jpg"

    hidecredits = false
    hidecopyright = false

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/cedi/"

[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 2
    url = "https://instagram.com/creativecedi/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"

[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"